name: EXAMEN_CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup compose
        uses: php-actions/composer@v6
        with:
          composer-version: 2.7.1

      - name: install dependences
        run: composer install

      - name: pruebas unitarias
        run: composer test

      - name: run code lint
        run: composer lint
